name: Release Extension

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: ./*.zip
          tag_name: v${{ github.ref }}
          title: Release ${{ github.ref }}
          body: |
            Changes in this release:
            - Add new feature
            - Fix bug
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
